url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
title: "Data Driven Developer" # the name of your site, e.g. ACME Corp.
email:
author:
description: How-tos, tips, and thoughts about the intersection of data science and software engineering. 

port: 4011

# Build settings
permalink: :title/
sass:
  sass_dir: _sass
